name: Upload S3
description: 'Upload directory to S3'
author: 'Dong Keon Kim'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'aws key id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'aws secret access key'
    required: true
  AWS_S3_BUCKET:
    description: 'aws bucket name'
    required: true
  SOURCE_DIR:
    required: true
    description: 'directory to upload'
  DEST_DIR:
    required: false
    default: /
    description: 'destination directory for upload'
outputs:
  object_key:
    description: 'object key'
  object_locations:
    description: 'object locations'
runs:
  using: 'node12'
  main: 'dist/index.js'
